version: "3.8"
services:
  app:
    build:
      args:
        user: ibbruser
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ibbr
    container_name: ibbr-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - ibbrnet

  db:
    image: mysql:8.0
    container_name: ibbr-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - ibbrnet

  nginx:
    image: nginx:1.25-alpine
    container_name: ibbr-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - ibbrnet

volumes:
  mysql_data: {}

networks:
  ibbrnet:
    driver: bridge